### ISSUE TITLE
Upgrade to R 3.5.3

### ISSUE THREAD

**Issue by RolandASc** [miraisolutions/SmaRP#91]
Dependency upgrade, i.e. specifically in the Dockerfile.
At the same time, possibly check / review the handling of dependencies for guaranteed reproducibility and allow alignment of development versions of packages with what would be built / deployed through the Dockerfile.

(See in particular https://hub.docker.com/r/rocker/r-ver/dockerfile and the use of `BUILD_DATE` and **MRAN**.)

**Comment by riccardoporreca** [comment]
@RolandASc, given R 3.6.0 is out, shall we then directly upgrade to 3.5.3, which will be soon available with fixed MRAN build date?

**Comment by RolandASc** [comment]
Yes, makes sense, let's do that

**Comment by riccardoporreca** [comment]
### Dockerfile considerations

Review and rethink the existing dependencies and their installation

- Required R package dependencies can be installed dynamically using `remotes::install_local()`
    - Still, there is the benefit in installing major, fixed depedencies like `shiny` and `dplyr` in a layer before the `COPY` to leverage caching and shared layers among different builds.
- Existing `apt-get` installations to be reviewed (not all might be needed). See below for some specific coments
- Do not rely on `texlive-full`, which is huge. Instead, use the portable, light-weight [TinyTeX](https://yihui.name/tinytex/). This can be done by extracting the relevant parts from [`rocker/verse/Dockerfile`](https://github.com/rocker-org/rocker-versioned/blob/master/verse/Dockerfile). Note however that automatic cropping of R plots via `pdfcrop` is not part of the default TinyTeX installation (yihui/tinytex#118). Besides `pdfcrop`, we want to make sure all needed LaTeX pkgs (e.g. `fancyhdr`) are installed in the Dockerfile. Otherwise they will be installed on-the fly and the first user generating the report will have to wait for a few minutes!
- Do not install `pandoc` through `apt-get`, but get a more recent [recommended](https://github.com/rstudio/rmarkdown/blob/master/PANDOC.md) version following new [instructions for Linux](https://pandoc.org/installing.html#linux). Version-specific .deb installers available for each [release](https://github.com/jgm/pandoc/releases), it might be good to use the same version as in `rocker/rstudio:3.5.3`.
